// include/ErrorCodes.h

#ifndef ERRORCODES_H
#define ERRORCODES_H

// Define unique codes for errors and debug messages
#define ERROR_STACK_OVERFLOW 1001
#define ERROR_MUTEX_CREATION_FAIL_SERVO 1002
#define ERROR_MUTEX_CREATION_FAIL_FEEDBACK 1003
#define ERROR_SCHEDULER_START_FAIL 1004
#define ERROR_DELAYED_CONTROL_LOOP 1005
#define ERROR_TAKE_FEEDBACK_MUTEX_SENDDATA 1006
#define ERROR_TAKE_FEEDBACK_MUTEX_PROCESSI2C 1007
#define ERROR_MALFORMED_INPUT_BUFFER 1008
// Add more error codes as needed

#define DEBUG_SERIAL_INIT 2001
#define DEBUG_SOFTWIRE_INIT 2002
#define DEBUG_PWM_INIT 2003
#define DEBUG_SERVO_INIT 2004
#define DEBUG_TASK_START_CONTROL 2005
#define DEBUG_TASK_START_SERIAL 2006
#define DEBUG_TASK_START_I2C 2007
#define DEBUG_CONTROL_LOOP_START 2008
#define DEBUG_CONTROL_LOOP_COMPLETE 2009
#define DEBUG_SERIAL_DATA_AVAILABLE 2010
#define DEBUG_SERIAL_CYCLE_COMPLETE 2011
#define DEBUG_I2C_REQUEST 2012
#define DEBUG_I2C_CYCLE_COMPLETE 2013
#define DEBUG_READING_ANALOG 2014
#define DEBUG_COMPUTING_CONTROL 2015
#define DEBUG_UPDATING_SERVOS 2016
#define DEBUG_COMMAND_START 2017
#define DEBUG_COMMAND_END 2018
#define DEBUG_FEEDBACK_SENT 2019
#define DEBUG_I2C_DATA_RECEIVED 2020
#define DEBUG_FEEDBACK_UPDATED 2021
#define DEBUG_I2C_NO_DATA 2022
// Add more debug codes as needed


#endif // ERRORCODES_H